### ISSUE TITLE
Text Contrast Errors for Foreground and Background Colors 

### ISSUE THREAD

**Issue by mtribone** [samvera/hyrax#1962]
### Descriptive summary

In Hyrax 2.0.0 rc1 and on the dashboard, there are several text contrast errors for the foreground and background colors.

### Rationale

Adequate contrast is necessary for all users, especially users with low vision or forms of color blindness.

### Expected behavior

Expected at least AA Compliance of all text colors.
https://webaim.org/standards/wcag/checklist#sc1.4.3

### Actual behavior

Text color in banner, breadcrumb link color and text color , previous and next link color for pagination, search placeholder text, transfer link text don't have sufficient contrast. 

![screen shot 2017-10-25 at 2 13 56 pm](https://user-images.githubusercontent.com/4163828/32015541-628f4d02-b98f-11e7-880a-8d9966178332.png)

### Steps to reproduce the behavior

1. Run an accessibility validator or color contrast validator
1. Review report on contrast errors

**Comment by mjgiarlo** [comment]
@mtribone Can you suggest colors for these changes?

**Comment by mtribone** [comment]
The purple banner at the top will pass AA if we darken it a bit (#6b6bb6). The same goes for the foreground color of the breadcrumb text, pagination text of prveious/next, and search for a user or placeholder text in general (#686868).  The linked home and select works to transfer seem to be false positives and are good to go.

**Comment by h-parekh** [comment]
1. Text color in banner:
  - Cannot reproduce in Vanilla Hyrax, this is specific to Nurax. 
  - `TODO`: change navbar to a darker shade in Nurax

2. breadcrumb link color (Home `<a>` tag)
  - This is meeting the contrast ratio for WCAG AA and AAA standards (See attached screenshot)
  - `TODO`: @mtribone  Is this a false alarm?

3. breadcrumb link color and text color
- `TODO`: Make the color of the text darker. Text color is being set by bootstrap CSS v3.3.7 in application.css
```css
# Current:
.breadcrumb>.active {
    color: #777777;
}
# Change to:
.breadcrumb>.active {
    color: #494949;
}
```
4. previous and next link color for pagination
  - `TODO`: Make the color of the text darker. Text color is being set by bootstrap CSS v3.3.7 in application.css
```css
# Current:
.pagination>.disabled>span, .pagination>.disabled>span:hover, .pagination>.disabled>span:focus, .pagination>.disabled>a, .pagination>.disabled>a:hover, .pagination>.disabled>a:focus {
    color: #777777;
    background-color: #fff;
    border-color: #ddd;
    cursor: not-allowed;
}
# Change to:
.pagination>.disabled>span, .pagination>.disabled>span:hover, .pagination>.disabled>span:focus, .pagination>.disabled>a, .pagination>.disabled>a:hover, .pagination>.disabled>a:focus {
    color: #595959;
    background-color: #fff;
    border-color: #ddd;
    cursor: not-allowed;
}
```
5. search placeholder text
  - `TODO`: Make the color of the text darker. Text color is being set by bootstrap CSS v3.3.7 in application.css
```css
# Current:
.select2-default {
    color: #999 !important;
}
# Change to:
.select2-default {
    color: #5f5d5d !important;
}
```
6. Transfer link text
  - Cannot reproduce in Vanilla Hyrax
  - `TODO`: Change text color settings in Nurax

I thought about a couple of options to fix 3,4,5:
- [Upgrading to bootstrap v4](https://medium.com/@sarahcodes/accessibility-issues-to-watch-out-for-in-bootstrap-4-962b993f0c64) will not fix these issues. 

- Add an additional hyrax_a11y.css file to the Hyrax application: That way even if we upgrade bootstrap at any point we will still continue to have these changes. Also, this can serve as a single point for all a11y changes, perhaps?

@mtribone @adamjarling  Thoughts?
